config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  devise_for 
    resources :users
  
  get 'welcome/index'
  get 'welcome/about'
  get 'welcome/legal'
  get 'sponsors/info'
  
  resources :charges, only: [:new, :create]

    resources :properties 
    resources :propimages, controller: 'properties/propimages'
    resources :extra, controller: 'properties/extras'
   

  resources :sponsors
  resources :leadership_team_members
  
  authenticated :user do
    root to: 'properties#index', as: :authenticated_root
  end

  root to: 'welcome#index'

end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
	has_many :properties
	belongs_to :User
	mount_uploader :logo, LogoUploader

  def synopsis=(val)
  	write_attribute(:synopsis, val.gsub(/[\r]/, "\n\r"))
  end


end

app/controllers/sponsors_controller.rb
class SponsorsController < ApplicationController
  def index
    
  end

  def info
    if current_user && current_user.role == 'sponsor'
      redirect_to new_sponsor_path
    end
  end

  def show
    @sponsor = Sponsor.find(params[:id])
    @leaders = Leadership_team_member.where(sponsor_id: @sponsor.id)  
    unless current_user && @sponsor.user_id == current_user.id
      flash[:alert] = "You do not have permission to access that site area"
      redirect_to sponsors_info_path
    end
    @properties = Property.where(:sponsor_id => @sponsor.id)
  end

  def new
    if current_user && current_user.role == 'sponsor' && current_user.sponsor_id == nil
  	  @sponsor = Sponsor.new
    elsif current_user.sponsor_id != nil
      redirect_to :controller => 'sponsors', :action => 'show', :id => current_user.sponsor_id
    else
      flash[:alert] = "You must become a premium member to access this part of the site."
      redirect_to sponsors_info_path
    end
  end

  def create
  	@sponsor = Sponsor.create(sponsor_params)
    @sponsor.update_attributes(user_id: current_user.id)
    current_user.update_attributes(sponsor_id: @sponsor.id)
  	if @sponsor.save
  		redirect_to @sponsor
  	else
  		flash[:alert] = "error creating Sponsor"
  		render :new
  	end
  end

  def destroy
    @sponsor = Sponsor.find(params[:id])
    if @sponsor.destroy
      flash[:notice] = "The sponsor has been deleted."
      redirect_to root_path
    else
      flash[:alert] = "An error occured and your sponsor was not deleted, please try again."
      render :edit
    end
  end

  def edit
  	@sponsor = Sponsor.find(params[:id])
    unless current_user && @sponsor.user_id == current_user.id
      redirect_to index_sponsor_path
    end
  end

  def update
    @sponsor = Sponsor.find(params[:id])
      if @sponsor.update_attributes(sponsor_params)
      	flash[:notice] = "Update successful"
      	redirect_to sponsor_path
      else
      	flash[:notice] = "Error updating Sponsor"
      	render :new
      end
  end
  private

  def sponsor_params
    params.require(:sponsor).permit(:name, :logo, :synopsis, :address_street, :address_city, :address_state, :address_zipcode, :phone_number, :website, :user_id)
  end
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/views/sponsors/edit.html.erb
<div class="row">
  <div class="col-md-1 col-sm-1"></div>
  <div class="col-md-4 col-sm-4 editPages">
  	<img src="<%= @sponsor.logo %>" class="sponsorLogo" height="100" alt="Logo" />
    <p class="sponsorName"><%= @sponsor.name %></p>

    <p class="sponsorAddress"><%= @sponsor.address_street %><br>
    <%= @sponsor.address_city %>, <%= @sponsor.address_state %> <%= @sponsor.address_zipcode %></p>
    <p class="sponsorPhone"><%= toPhone(@sponsor.phone_number) %></p>
    <p class="sponsorWebsite"><a href="http://<%= @sponsor.website %>" target="_blank"><%= @sponsor.website %></a></p>
    <div class="sponsorSynopsis"><%= markdown_to_html @sponsor.synopsis %></div>
  </div>
  <div class="col-md-1 col-sm-1"></div>
  <div class="col-md-4 col-sm-4 editPages">
    <h2>Edit Sponsor</h2>
    <%= form_for @sponsor do |f| %>
      <p>
        <%= f.label :name %>
	    <%= f.text_field :name, class: 'form-control', required: true, placeholder: "Company Name" %>
      </p>
      <p>Address</p>
      <div class="row">
      <div class="col-md-12 col-sm-12">
      <p>
        <%= f.label "Street" %>
        <%= f.text_field :address_street, class: 'form-control', required: true, placeholder: "Street Address" %>
      </p>
      </div>
      <div class="col-md-6">
      <p>
        <%= f.label "City" %>
        <%= f.text_field :address_city, class: 'form-control', required: true, placeholder: "City" %>
      </p>
      </div>
      <div class="col-md-3">
      <p>
        <%= f.label "State" %>
        <%= f.text_field :address_state, class: 'form-control', required: true, placeholder: "State" %>
      </p>
      </div>
      <div class="col-md-3">
      <p>
        <%= f.label "Zipcode" %>
        <%= f.text_field :address_zipcode, class: 'form-control', required: true, placeholder: "zipcode" %>
      </p>
      </div>
      </div>
      <p>
        <%= f.label :phone_number %>
        <%= f.text_field :phone_number, class: 'form-control', required: true, placeholder: "123-456-7890" %>
      </p>
      <p>
        <%= f.label :website %>
        <%= f.text_field :website, class: 'form-control', required: true, placeholder: "www.example.com" %>
      </p>
      <p>
        <%= f.label :synopsis %>
        <%= f.text_area :synopsis, rows: 8, cols: 45, class: 'form-control markdown-toolbar', placeholder: "Enter synopsis here" %>
      </p>
      <p>
        <%= f.label :logo %>
        <%= f.file_field :logo %>
        <%= f.hidden_field :logo_cache %>
      </p>
      <p>
      <%= f.submit "Save Profile", class: 'btn btn-success' %>
      </p>
    <% end %>


  </div>


</div>

app/views/sponsors/info.html.erb
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8 col-sm-8 welcomeMessage">
    <h2>Are you looking to become a sponsor for a property listing?</h2>
    <p>Register as a Sponsor.  We charge $50.00 a month to host as many properties as you would like.  Eventually we will charge 2% of the purchase price of your property and eventually Chris will get is Audi.</p>
    <%= link_to "Create Sponsorship", new_charge_path, class: 'btn btn-warning' %>
  </div>

</div>

app/views/sponsors/new.html.erb
<div class="row">
 
  <div class="col-md-4 col-sm-4"></div>
  <div class="col-md-4 col-sm-4 editPages">
  <h2>Become a Sponsor</h2>
    <%= form_for @sponsor do |f| %>
      <p>
        <%= f.label :name %>
	    <%= f.text_field :name, class: 'form-control', required: true, placeholder: "Company Name" %>
      </p>
      <p>Address</p>
    <div class="row">
      <div class="col-md-12 col-sm-12">
      <p>
        <%= f.label "Street" %>
        <%= f.text_field :address_street, class: 'form-control', required: true, placeholder: "Street Address" %>
      </p>
      </div>
      <div class="col-md-6">
      <p>
        <%= f.label "City" %>
        <%= f.text_field :address_city, class: 'form-control', required: true, placeholder: "City" %>
      </p>
      </div>
      <div class="col-md-3">
      <p>
        <%= f.label "State" %>
        <%= f.text_field :address_state, class: 'form-control', required: true, placeholder: "State" %>
      </p>
      </div>
      <div class="col-md-3">
      <p>
        <%= f.label "Zipcode" %>
        <%= f.text_field :address_zipcode, class: 'form-control', required: true, placeholder: "zipcode" %>
      </p>
      </div>
      </div>
      <p>
        <%= f.label :phone_number %>
        <%= f.text_field :phone_number, class: 'form-control', required: true, placeholder: "123-456-7890" %>
      </p>
      <p>
        <%= f.label :website %>
        <%= f.text_field :website, class: 'form-control', required: true, placeholder: "www.example.com" %>
      </p>
      <p>
        <%= f.label :synopsis %>
        <%= f.text_area :synopsis, rows: 8, cols: 45, class: 'form-control markdown-toolbar', placeholder: "Enter synopsis here" %>
      </p>
      <p>
        <%= f.label :logo %>
        <%= f.file_field :logo %>
        <%= f.hidden_field :logo_cache %>
      </p>
      <p>
      <%= f.submit "Save Profile", class: 'btn btn-success' %>
      </p>
    <% end %>
  </div >
</div>
<script type="text/javascript">
            $().ready(function() {
               $("#notes").wmd(); 
            });
        </script>

app/views/sponsors/show.html.erb
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-2 col-sm-2 editPages">
    <% if @properties.present? %>
      <h3>Your Properties</h3>
      <ul class="yourProperties">
      <% @properties.each do |property| %>
        <li><%= link_to property.name, [:edit, property] %></li>
      <% end %>
      </ul>
    <% end %> 
    <%= link_to("Create A Property", new_property_path , class: 'btn btn-success') %>
  </div>
    <div class="col-md-1 col-sm-1"></div>
  <div class="col-md-6 col-sm-6 editPages">

    <img src="<%= @sponsor.logo %>" class="sponsorLogo" width="100" alt="Logo" />
    <p class="sponsorName"><%= @sponsor.name %></p>

    <p class="sponsorAddress"><%= @sponsor.address_street %><br>
    <%= @sponsor.address_city %>, <%= @sponsor.address_state %> <%= @sponsor.address_zipcode %></p>
    <p class="sponsorPhone"><%= toPhone(@sponsor.phone_number) %></p>
    <p class="sponsorWebsite"><a href="http://<%= @sponsor.website %>" target="_blank"><%= @sponsor.website %></a></p>
    <div class="sponsorSynopsis"><%= markdown_to_html @sponsor.synopsis %></div>
      <%= link_to "Modify your Sponsor Page", edit_sponsor_path, class: 'btn btn-danger' %>

    <div class="leaderTeamBox">  
      <p><%= link_to "Create a Team Member", new_leadership_team_member_path, class: 'btn btn-success' %></p>
      <% if @leaders.present? %>
        <% @leaders.each do |leader| %>
          <div class="leaderBox">
            <img src="<%= leader.picture %>" height="100" width='100' class="ltm_picture" />
            <span class="leaderName"> <%= leader.name %></span>
            <%= markdown_to_html leader.synopsis %>
          </div>
        <%= link_to "Delete Team Member", leader, method: :delete, data: {confirm: "Are you sure you wish to delete this team member?"}, class: "btn btn-danger" %>
        <% end %>
      <% end %>
    </div>


  </div>

</div>