config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  devise_for 
    resources :users
  
  get 'welcome/index'
  get 'welcome/about'
  get 'welcome/legal'
  get 'sponsors/info'
  
  resources :charges, only: [:new, :create]

    resources :properties 
    resources :propimages, controller: 'properties/propimages'
    resources :extra, controller: 'properties/extras'
   

  resources :sponsors
  resources :leadership_team_members
  
  authenticated :user do
    root to: 'properties#index', as: :authenticated_root
  end

  root to: 'welcome#index'

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def create

    #creates a stripe customer object, for associating with the charge
	customer = Stripe::Customer.create(
	  email: current_user.email,
	  card: params[:stripeToken]
	)

	  #Where the real magic happens
	charge = Stripe::Charge.create(
	  customer: customer.id, #Note -- this is NOT the user_id in your app
	  amount: Amount.default,
	  description: "Sponsorship - #{current_user.email}",
	  currency: 'usd'
	)
	current_user.update_attribute(:role, 'sponsor')
	flash[:success] = "Thank you for your payment, #{current_user.email}! Please fill out this sponsor form!"
	redirect_to new_sponsor_path

	  #Stripes friendly error blocks

	rescue Stripe::CardError => e 
	  flash[:error] = e.message
	  redirect_to new_charge_path
  end

  def new
  	if current_user
      @stripe_btn_data = {
        key: "#{ Rails.configuration.stripe[:publishable_key] }",
        description: "Sponsorship - #{current_user.email}",
        amount: Amount.default
      }
    else
      flash[:alert] = "Please create a free account before purchasing a sponsor account."
      redirect_to new_user_registration_path
    end      
  end

private

  class Amount
  	@default_amount = 5000
  	  def self.default
  		@default_amount
  	  end
  end


end

app/views/charges/new.html.erb
 <div class="row">
  <div class="col-md-2 col-sm-2"></div>
  <div class="col-md-4 col-sm-4 fullBackground">
  <p>Before you purchase a sponsorship please be sure that you understand our policy and user agreement.  The key to our mutual success is found in our ability to communicate with each other.</p>
    <p>I have read and agree to the <a href="#" target="_blank">Sponsors Policy</a>: 
     <input type="checkbox" id="policyCheck" style="margin-left:10px;">
    </p>
	 <%= form_tag charges_path do %>
       <div id="scriptDiv" style="display:none;">  
	     <h4>Purchase your Sponsor Membership</h4>   
		    <script class="stripe-button" src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" >
		    /*This is here */ 
		   </script> 
		   </div>

    <% end %>

  </div>
 </div>