config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  devise_for 
    resources :users
  
  get 'welcome/index'
  get 'welcome/about'
  get 'welcome/legal'
  get 'sponsors/info'
  
  resources :charges, only: [:new, :create]

    resources :properties 
    resources :propimages, controller: 'properties/propimages'
    resources :extra, controller: 'properties/extras'
   

  resources :sponsors
  resources :leadership_team_members
  
  authenticated :user do
    root to: 'properties#index', as: :authenticated_root
  end

  root to: 'welcome#index'

end

app/views/layouts/_footer.html.erb
<footer>
  <div class="row hidden-xs">
    <div class="col-md-3 col-sm-2"></div>
      <div class="col-md-2 col-sm-3">
        <ul><span class="titles">Policies</span>
          <li>Terms of Use</li>
          <li>Privacy Policy</li>
          <li>Posting Policy</li>
        </ul>
      </div>
      <div class="col-md-2 col-sm-3">
        <ul><span class="titles">Contact Us</span>
          <li>888.123.4567</li>
          <li><a href="mailto:contact@apartmentfunder.com">Email Us</a></li>
        </ul>
      </div>
      <div class="col-md-2 col-sm-2">
        <ul><span class="titles">Get Social</span>
          <li>Facebook</li>
          <li>Twitter</li>
          <li>LinkedIn</li>
        </ul>
      </div>
      <div class="col-md-3 col-sm-2"></div>
  </div>

  <div class="row visible-xs">
    <div class="col-xs-12 mobileFooter">
      <a href="#" class="mobileLinks">Terms</a>
      <a href="#" class="mobileLinks">Privacy</a>
      <a href="#" class="mobileLinks">Posting</a>
      <a href="#" class="mobileLinks">Contact</a>
     <p></p>     
      <a href="#" class="mobileSocialLinks"><img src="https://s3.amazonaws.com/apartmentfunder-development/images/facebook-24.png" height="25" width="25" alt="Facebook"></a> 
      <a href="#" class="mobileSocialLinks"><img src="https://s3.amazonaws.com/apartmentfunder-development/images/twitter-24.png" height="25" width="25" alt="Twitter"></a>
      <a href="#" class="mobileSocialLinks"><img src="https://s3.amazonaws.com/apartmentfunder-development/images/icon-linkedin-25px.png" height="25" width="25" alt="LinkedIn"></a>
      <p>888.123.4567</p>
    </div>
  </div>
    <div class="centeredRow">
    <p id="disclaimBtn">Disclaimer</p>
  </div>
  <div id="disclaimer">
    <p>Use, reproduce, modify, display, perform, sublicense and distribute this software may accept certain responsibilities for you if you were not explicitly requested by the Derivative Works; and If the search is unsuccessful or no action to resume active maintenance is taken by the Licensed Product. If you assert a patent applicable to Covered Code available to Licensee on an "AS IS" AND ANY EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF OR IN CONNECTION WITH THE SOFTWARE. Preamble The licenses for most software are designed to take over maintenance. Work identifies itself to the terms set forth herein, no assurances are provided by any other Contributor, and only if you fail to comply with any other party who may distribute the Program, modifications to it, including all modules contained therein, plus any associated interface definition files, scripts used to render or display fonts. Program" shall mean any work based on the same sections as part of the Work, copying of components of the date of any Derivative Works from it.</p>
    <p>Works" is defined in Article 1 (Definitions) 1. Font Program" shall mean products provided to end users in the province of Quebec, Canada, the following in a location (such as a relevant directory) where a Digital Document File. One line to give attribution in the LEGAL file in all copies of Original Code without infringement; and (b) are effective on the Program, and includes a "NOTICE" text file with the license, the text you import may be distributed.</p>
    <p>We, the LaTeX3 Project, believe that the Package in object code and object code form. Subject to the three files `pig.dtx', `pig.ins', and `pig.sty' (the last being generated from `pig.dtx' using `pig.ins'), the `Base Interpreter' referring to any patent claim(s), now owned or controlled by You, to use, copy, modify, and distribute the Program not expressly granted under this Agreement as released by IBM, including source code, fonts, documentation, graphics, sound etc.) and the preferred form of digital data, including video content, motion and/or still pictures, TV programs or works based on infringement of intellectual property rights needed, if any. For example, a Distributor Fee, and with or without Modifications, and/or any respective portions thereof.</p>
  </div>
<%
=begin %>
  <div class="row">

    <div class="col-md-2">
      <ul><span class="titles">Links</span>
        <li>About Us</li>
        <li>Listings</li>
        <li>Sponsors</li>
      </ul>
    </div>
    <div class="col-md-2">
      <ul><span class="titles">Policies</span>
        <li>Terms of Use</li>
        <li>Privacy Policy</li>
        <li>Posting Policy</li>
      </ul>
    </div>
    <div class="col-md-2">
      <ul><span class="titles">Contact Us</span>
        <li>888.123.4567</li>
        <li><a href="mailto:contact@apartmentfunder.com">Email Us</a></li>
      </ul>
    </div>

    <div class="col-md-2">
      <ul><span class="titles">Get Social</span>
        <li>Facebook</li>
        <li>Twitter</li>
        <li>LinkedIn</li>
      </ul>
    </div>
  </div>
  <div class="centeredRow">
    <p id="disclaimBtn">Disclaimer</p>
  </div>
  <div id="disclaimer">
    <p>Use, reproduce, modify, display, perform, sublicense and distribute this software may accept certain responsibilities for you if you were not explicitly requested by the Derivative Works; and If the search is unsuccessful or no action to resume active maintenance is taken by the Licensed Product. If you assert a patent applicable to Covered Code available to Licensee on an "AS IS" AND ANY EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF OR IN CONNECTION WITH THE SOFTWARE. Preamble The licenses for most software are designed to take over maintenance. Work identifies itself to the terms set forth herein, no assurances are provided by any other Contributor, and only if you fail to comply with any other party who may distribute the Program, modifications to it, including all modules contained therein, plus any associated interface definition files, scripts used to render or display fonts. Program" shall mean any work based on the same sections as part of the Work, copying of components of the date of any Derivative Works from it.</p>
    <p>Works" is defined in Article 1 (Definitions) 1. Font Program" shall mean products provided to end users in the province of Quebec, Canada, the following in a location (such as a relevant directory) where a Digital Document File. One line to give attribution in the LEGAL file in all copies of Original Code without infringement; and (b) are effective on the Program, and includes a "NOTICE" text file with the license, the text you import may be distributed.</p>
    <p>We, the LaTeX3 Project, believe that the Package in object code and object code form. Subject to the three files `pig.dtx', `pig.ins', and `pig.sty' (the last being generated from `pig.dtx' using `pig.ins'), the `Base Interpreter' referring to any patent claim(s), now owned or controlled by You, to use, copy, modify, and distribute the Program not expressly granted under this Agreement as released by IBM, including source code, fonts, documentation, graphics, sound etc.) and the preferred form of digital data, including video content, motion and/or still pictures, TV programs or works based on infringement of intellectual property rights needed, if any. For example, a Distributor Fee, and with or without Modifications, and/or any respective portions thereof.</p>
  </div>
  <%
=end %>
  <p class="legal">Copyright &copy 2015 All Rights Reserved, ApartmentFunder LLC</p>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Apartment Funder</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
<!--FAVICON SETS -->
  <link rel="apple-touch-icon" sizes="57x57" href="https://s3.amazonaws.com/apartmentfunder-production/images/apple-icon-57x57.png">
  <link rel="apple-touch-icon" sizes="60x60" href="https://s3.amazonaws.com/apartmentfunder-production/images/apple-icon-60x60.png">
  <link rel="apple-touch-icon" sizes="72x72" href="https://s3.amazonaws.com/apartmentfunder-production/images/apple-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="76x76" href="https://s3.amazonaws.com/apartmentfunder-production/images/apple-icon-76x76.png">
  <link rel="apple-touch-icon" sizes="114x114" href="https://s3.amazonaws.com/apartmentfunder-production/images/apple-icon-114x114.png">
  <link rel="apple-touch-icon" sizes="120x120" href="https://s3.amazonaws.com/apartmentfunder-production/images/apple-icon-120x120.png">
  <link rel="apple-touch-icon" sizes="144x144" href="https://s3.amazonaws.com/apartmentfunder-production/images/apple-icon-144x144.png">
  <link rel="apple-touch-icon" sizes="152x152" href="https://s3.amazonaws.com/apartmentfunder-production/images/apple-icon-152x152.png">
  <link rel="apple-touch-icon" sizes="180x180" href="https://s3.amazonaws.com/apartmentfunder-production/images/apple-icon-180x180.png">
  <link rel="icon" type="image/png" sizes="192x192"  href="https://s3.amazonaws.com/apartmentfunder-production/images/android-icon-192x192.png">
  <link rel="icon" type="image/png" sizes="32x32" href="https://s3.amazonaws.com/apartmentfunder-production/images/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="96x96" href="https://s3.amazonaws.com/apartmentfunder-production/images/favicon-96x96.png">
  <link rel="icon" type="image/png" sizes="16x16" href="https://s3.amazonaws.com/apartmentfunder-production/images/favicon-16x16.png">
  <link rel="manifest" href="https://s3.amazonaws.com/apartmentfunder-production/images/manifest.json">
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="msapplication-TileImage" content="https://s3.amazonaws.com/apartmentfunder-production/images/ms-icon-144x144.png">
  <meta name="theme-color" content="#ffffff">
</head>
<body>
<div id="wrapper">
    <header>
<nav class="navbar navbar-default" style="background-color:white; border-bottom:none;">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">
        <img src="https://s3.amazonaws.com/apartmentfunder-development/images/headerLogoModCenterHigh.jpg" height="75" style="padding:0; margin:0;">
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
          <li><%= link_to 'About Us', root_path, class: 'topMenu' %></li>
          <li><%= link_to 'Listings', properties_path, class: 'topMenu' %></li>
          <li><%= link_to 'Sponsors', sponsors_info_path, class: 'topMenu' %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <% if current_user %>
              <% if current_user.avatar_url == nil %>
                <%= current_user.name != nil ? current_user.name : current_user.email %> <span class="caret"></span></a>  
              <% else %>
                <img src='<%= current_user.avatar %>' height="35" class="loginIcon"> <span class="caret"></span></a>  
              <% end %>
              
              <ul class="dropdown-menu">
                <li><%= link_to 'Investments', '#' %></li>
                <li><%= link_to 'Account', edit_user_registration_path %></li>
                <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
              </ul>        
            <% else %>
              <img src='https://s3.amazonaws.com/apartmentfunder-development/images/Portrait_placeholder.png' height="35" class="loginIcon"> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li class="login"><%= link_to "Sign Up", new_user_registration_path %></li>
            <li class="login"><%= link_to "Log In", new_user_session_path %></li> 
            <!-- <li role="separator" class="divider"></li> -->
          </ul>
          <% end %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<%
=begin %>    
      <div class="logoMain"><img src="https://s3.amazonaws.com/apartmentfunder-development/images/headerLogoModCenterHigh.jpg" height="100"/></div>
        <ul class="leftNav navLinks">
          <li><%= link_to 'About Us', root_path %></li>
          <li><%= link_to 'Listings', properties_path %></li>
          <li><%= link_to 'Sponsors', sponsors_info_path %></li>
          <li><a href="#">Contact</a></li>
        </ul>
        <ul class="rightNav">
        <% if current_user %>
          <li class="userName">
            <%= current_user.name != nil ? current_user.name : current_user.email %> </li>
          <ul class='underName'>
          <li><%= link_to 'Investments', '#' %></li>
          <li><%= link_to 'Account', edit_user_registration_path %></li>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          </ul>
        <% else %>
          <li class="login"><%= link_to "Sign Up", new_user_registration_path %></li>
          <li class="login"><%= link_to "Log In", new_user_session_path %></li> 
        <% end %>
        </ul>
<%
=end %>
    </header>
 <div class="contentHolder"> 
    <div class="flash">
      <% if flash[:notice] %>
        <div class="alert alert-success"><%= notice %></div>
      <% elsif flash[:alert] %>
        <div class="alert alert-danger"><%= alert %></div>
      <% end %>
    </div>

    <%= yield %>
 </div><!--End ContentHolder-->
  <%= render "layouts/footer" %>
  </div>
</body>
</html>